require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'

Style:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Gemspec/RequiredRubyVersion:
  Enabled: false

Bundler/GemFilename:
  Enabled: false
